[project]
name = "nmnist-surrogate"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.5",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
